name: Build Windows EXE
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      -       - name: Build EXE with PyInstaller
        run: pyinstaller --noconfirm --noconsole --onefile --hidden-import=tkinter --name DiskGuardian main.py


      - name: Build EXE
        run: |
          pyinstaller --noconfirm --noconsole --onefile ^
            --name DiskGuardian ^
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DiskGuardian-EXE
          path: dist/DiskGuardian.exe
